# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df1ccbf676b2a08e33e6b4354ec23b82523abd4c9c2034cd2f329104aed2ad9358477fde5ba7afbc227f30ba642c5fefb6019c8fe4a0c1b1ef1dfe902129125d

test:
  secret_key_base: 2e499dae6f71d64ed1c1c7e526a614c8dada232857a65d285fe0d213d176138f1235307c80adcf66ab5d6ce37d8492866f9c651f4b039773f6e59a26693bddc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
